language: python
python:
  - "3.9"

services:
  - docker
  - postgresql
  - redis

branches:
  only:
    - travis

before_script:
  - docker compose up

script:
  - python3 app.py

notifications:
  email:
    recipients:
      - iryna.yarka@gmail.com
      - project.franchise2021@gmail.com
    on_success: never
    on_failure: always
