language: python
python:
  - "3.9"

services:
  - docker
  - redis

addons:
  postgresql: "13.2"

branches:
  only:
    - travis

jobs:
  include:
    - env: CMD="/usr/local/bin/docker-compose --profile test up -d" DOCKER="true"

env:
  global:
  - PGPORT=5482

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.29.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo systemctl start postgresql
  - systemctl status postgresql.service
  - sudo service postgresql start
  - pg_lsclusters
  - psql -c 'create database test;' -U postgres
  - psql -c "CREATE USER lv-python-mc WITH PASSWORD '575';" -U postgres

before_script:
  - pip install docker-compose
  - docker-compose up -d

script:
  - python3 -m pytest tests/test.py

after_script:
  - docker-compose down

notifications:
  email:
    recipients:
      - iryna.yarka@gmail.com
    on_success: never
    on_failure: always
