version: '3.9'

services:
  app:
    profiles: ["dev-python"]
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    env_file:
      - .flask_env
    environment:
      - CS_HOST_IP=0.0.0.0
      - DATABASE_URL=postgresql://lv-python-mc:575@db:5432/Realty_DB
      - REDIS_IP=redis
      - DOMRIA_API_KEYS=${DOMRIA_API_KEYS}

  db:
    image: postgres:13.2
    profiles: ["dev", "dev-python"]
    ports:
      - "5482:5432"
    environment:
      - POSTGRES_USER=lv-python-mc
      - POSTGRES_PASSWORD=575
      - POSTGRES_DB=Realty_DB
    volumes:
      - flask_db_volume:/var/lib/postgresql/data
    external_links:
      - agregattor:0.0.0.0

  redis:
    profiles: ["dev", "dev-python"]
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - flask_redis_volume:/data

  db_test:
    profiles: ["test"]
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lv-python-mc
      - POSTGRES_PASSWORD=575
      - POSTGRES_DB=test


  redis_test:
    profiles: ["test"]
    image: redis:6.2
    ports:
      - "6379:6379"


volumes:
  flask_db_volume:
  flask_redis_volume:
