version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    env_file:
      - .flask_env
  
  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lv-python-mc
      - POSTGRES_PASSWORD=575
      - POSTGRES_DB=Realty_DB
    volumes:
      - flask_db_volume:/var/lib/postgresql/data
  
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - flask_redis_volume:/data

volumes:
  flask_db_volume:
  flask_redis_volume:
