version: '3.9'

services:
  db:
    image: postgres:13.2
    ports:
      - "5482:5432"
    environment:
      - POSTGRES_USER=lv-python-mc
      - POSTGRES_PASSWORD=575
      - POSTGRES_DB=test


  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
