version: '3.9'

services:
  app:
    profiles: ["dev-python", "python-celery"]
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    env_file:
      - .flask_env
    environment:
      - CS_HOST_IP=0.0.0.0
      - DATABASE_URL=postgresql://lv-python-mc:575@db:5432/Realty_DB
      - REDIS_IP=redis
      - DOMRIA_API_KEYS=${DOMRIA_API_KEYS}
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_worker:
    profiles: ["dev-python", "python-celery"]
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
      - app
    env_file:
      - .flask_env
    environment:
      - CS_HOST_IP=0.0.0.0
      - DATABASE_URL=postgresql://lv-python-mc:575@db:5432/Realty_DB
      - REDIS_IP=redis
      - DOMRIA_API_KEYS=${DOMRIA_API_KEYS}
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A service_api.celery_tasks.tasks.celery_app worker -B

  db:
    image: postgres:13.2
    profiles: ["dev", "dev-python", "python-celery"]
    ports:
      - "5482:5432"
    environment:
      - POSTGRES_USER=lv-python-mc
      - POSTGRES_PASSWORD=575
      - POSTGRES_DB=Realty_DB
    volumes:
      - flask_db_volume:/var/lib/postgresql/data

  redis:
    profiles: ["dev", "dev-python", "python-celery"]
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - flask_redis_volume:/data

  db_test:
    profiles: ["test"]
    image: postgres:13.2
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=lv-python-mc
      - POSTGRES_PASSWORD=575
      - POSTGRES_DB=test


  redis_test:
    profiles: ["test"]
    image: redis:6.2
    ports:
      - "6379:6379"


volumes:
  flask_db_volume:
  flask_redis_volume:
