"""RealtyDetails Set original url not unique

Revision ID: 3fdcde9df851
Revises: 97ab80b75a29
Create Date: 2021-05-04 08:04:58.192952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdcde9df851'
down_revision = 'a23a5ca33d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('realty_details_original_url_key', 'realty_details', type_='unique')
    op.create_unique_constraint(None, 'realty_details', ['original_url', 'version'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'realty_details', type_='unique')
    op.create_unique_constraint('realty_details_original_url_key', 'realty_details', ['original_url'])
    # ### end Alembic commands ###
