"""Request history added

Revision ID: 774af0a95683
Revises: 9deac691669d
Create Date: 2021-05-11 20:58:07.209175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774af0a95683'
down_revision = '9deac691669d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_history', sa.Column('url', sa.VARCHAR(length=4096), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests_history', 'url')
    # ### end Alembic commands ###
