"""categoryXrealty_type relation added

Revision ID: 97ab80b75a29
Revises: ea28a11e4797
Create Date: 2021-05-01 11:23:48.803872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ab80b75a29'
down_revision = 'ea28a11e4797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realty_type', sa.Column('category_id', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'realty_type', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'realty_type', type_='foreignkey')
    op.drop_column('realty_type', 'category_id')
    # ### end Alembic commands ###
