"""Nullable constrain updated in entites tables

Revision ID: 9deac691669d
Revises: 97ab80b75a29
Create Date: 2021-05-06 19:50:17.950414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9deac691669d'
down_revision = '97ab80b75a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('city', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('operation_type', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('realty_type', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('state', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('realty_type', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('operation_type', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('city', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('category', 'version',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
