"""Resolved triggers errors

Revision ID: bcc88fcccb0e
Revises: f1f211c9cdaa
Create Date: 2021-04-27 15:46:49.773524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc88fcccb0e'
down_revision = 'f1f211c9cdaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_state_id_fkey', 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'state', ['state_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key('city_state_id_fkey', 'city', 'service', ['state_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
