"""RequestsHistory added

Revision ID: d3ab13075552
Revises: 3fdcde9df851
Create Date: 2021-05-12 13:25:48.482542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ab13075552'
down_revision = '3fdcde9df851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_history',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=4096), nullable=False),
    sa.Column('hashed_token', sa.VARCHAR(length=200), nullable=False),
    sa.Column('request_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests_history')
    # ### end Alembic commands ###
