"""New models

Revision ID: e86132eb6677
Revises: 
Create Date: 2021-03-17 21:49:26.159403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86132eb6677'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_type',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('original_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realty_type',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('original_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('original_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('state_id', sa.BIGINT(), nullable=False),
    sa.Column('original_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('city_id', sa.BIGINT(), nullable=False),
    sa.Column('street_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('building_number', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realty',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('location_id', sa.BIGINT(), nullable=False),
    sa.Column('floor', sa.BIGINT(), nullable=False),
    sa.Column('floors_number', sa.BIGINT(), nullable=False),
    sa.Column('square', sa.BIGINT(), nullable=False),
    sa.Column('rental_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('building_state', sa.VARCHAR(length=255), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('original_id', sa.BIGINT(), nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('realty_type_id', sa.BIGINT(), nullable=False),
    sa.Column('operation_type_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['operation_type_id'], ['operation_type.id'], ),
    sa.ForeignKeyConstraint(['realty_type_id'], ['realty_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realty')
    op.drop_table('location')
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('realty_type')
    op.drop_table('operation_type')
    # ### end Alembic commands ###
